# Generated by Django 6.0.5 on 2026-05-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='Project',
            new_name='project',
        ),
    ]
