# Generated by Django 6.0.5 on 2026-05-31 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_project_auditlog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
    ]
