# Generated by Django 6.0.5 on 2026-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=20),
        ),
    ]
